language: python

dist: xenial

# cache:
#   pip: true
#   cargo: true

matrix:
  include:
    - name: Python 3.6
      python: "3.6"
    - name: Python 3.7
      python: "3.7"
    - name: Python 3.8
      python: "3.8"

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly --component clippy rustfmt

install:
   - pip install -U poetry pytest-cov
   - poetry install
   - cargo build
   - poetry run maturin build --release
   - poetry run pytest tests
  #  - pytest --cov=myproj tests/
  
after_success:
    - codecov
