language: python

dist: xenial

cache:
  pip: true
  cargo: true

matrix:
  include:
    - name: Python 3.6
      python: "3.6"
    - name: Python 3.7
      python: "3.7"
    - name: Python 3.8
      python: "3.8"

env:
  global:
    - TRAVIS_RUST_VERSION=nightly
    - RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

install:
   - pip install -U poetry pytest-cov
   - poetry install
   - poetry run maturin develop --release
   - pytest --cov=myproj tests/
  
after_success:
    - codecov
